# Configure the prompt
continuation_prompt = '$character '

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$line_break\
$character"""

right_format = """$all"""

[directory]
truncation_length = 3

[git_metrics]
disabled = false
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
format = '[$all_status$ahead_behind]($style)'
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
conflicted = '=${count} '
ahead = '⇡${count} '
behind = '⇣${count} '
untracked = '?${count} '
stashed = '${count} '
modified = '!${count} '
staged = '+${count} '
renamed = '»${count} '
deleted = '✘${count} '

