# Configure the prompt
continuation_prompt = '$character '

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

right_format = """$all"""

[directory]
truncation_length = 3

