# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = [workspace 2 silent] ghostty
exec-once = [workspace 1] zen-browser

exec-once = cd ~/Documents/Downloaded_Packages/fizzy/ && docker compose up -d &
# exec-once = [workspace 3] omarchy-launch-webapp http://localhost:8080

# exec-once = [workspace 4] omarchy-launch-webapp "https://3.basecamp.com/6139336/projects"
exec-once = [workspace 3] omarchy-launch-webapp "https://app.hey.com"

exec-once = uwsm app -- hyprsunset
